import { supabase } from '../supabase';
import { Brand } from '../../types/brand';

let supportedColumnsCache: Set<string> | null = null;

async function getSupportedBrandColumns(): Promise<Set<string> | null> {
  if (supportedColumnsCache && supportedColumnsCache.size > 0) {
    return supportedColumnsCache;
  }
  try {
    const { data } = await supabase.from('brands').select('*').limit(1);
    if (data && data.length > 0) {
      supportedColumnsCache = new Set(Object.keys(data[0]));
      return supportedColumnsCache;
    }
  } catch (err) {
    console.warn('Could not inspect brands schema columns:', err);
  }
  return null;
}

function prepareBrandPayload(brand: Partial<Brand>, supportedCols: Set<string> | null): Record<string, any> {
  const payload: Record<string, any> = { ...brand };

  // Always remove auto-generated / metadata fields from insert/update
  delete payload.created_at;
  delete payload.updated_at;

  // Harmonize status and is_active
  if (payload.status !== undefined && payload.is_active === undefined) {
    payload.is_active = payload.status === 'active';
  } else if (payload.is_active !== undefined && payload.status === undefined) {
    payload.status = payload.is_active ? 'active' : 'hidden';
  }

  // Filter against known columns if available
  if (supportedCols && supportedCols.size > 0) {
    for (const key of Object.keys(payload)) {
      if (!supportedCols.has(key)) {
        delete payload[key];
      }
    }
  }

  return payload;
}

export async function getBrands() {
  const { data, error } = await supabase
    .from('brands')
    .select('*')
    .order('name', { ascending: true });
    
  if (error) {
    console.error('Error fetching brands:', error);
    return [];
  }

  if (data && data.length > 0) {
    supportedColumnsCache = new Set(Object.keys(data[0]));
  }

  return (data || []).map((item: any) => ({
    ...item,
    status: item.status || (item.is_active !== false ? 'active' : 'hidden'),
    is_active: item.is_active !== undefined ? item.is_active : item.status === 'active',
  })) as Brand[];
}

export async function getBrand(id: string) {
  const { data, error } = await supabase
    .from('brands')
    .select('*')
    .eq('id', id)
    .single();
  if (error) throw error;

  return {
    ...data,
    status: data.status || (data.is_active !== false ? 'active' : 'hidden'),
    is_active: data.is_active !== undefined ? data.is_active : data.status === 'active',
  } as Brand;
}

export async function createBrand(brand: Partial<Brand>) {
  const supported = await getSupportedBrandColumns();
  const payload = prepareBrandPayload(brand, supported);
  delete payload.id; // ensure id is generated by db unless specified

  // Resilient insert with schema retry if PostgREST reports missing column
  let attemptPayload = { ...payload };
  for (let attempt = 0; attempt < 8; attempt++) {
    const { data, error } = await supabase
      .from('brands')
      .insert([attemptPayload])
      .select()
      .single();

    if (!error && data) {
      if (supportedColumnsCache) {
        Object.keys(data).forEach(k => supportedColumnsCache?.add(k));
      }
      return {
        ...data,
        status: data.status || (data.is_active !== false ? 'active' : 'hidden'),
      } as Brand;
    }

    if (error) {
      // Check if error is missing column in schema cache (PGRST204)
      const missingMatch = error.message?.match(/Could not find the '([^']+)' column of 'brands'/i);
      if (missingMatch && missingMatch[1]) {
        const missingCol = missingMatch[1];
        console.warn(`Brand insert: column '${missingCol}' missing in DB schema cache. Stripping and retrying.`);
        delete attemptPayload[missingCol];
        continue;
      }
      throw error;
    }
  }
  throw new Error('Failed to create brand after schema retries');
}

export async function updateBrand(id: string, brand: Partial<Brand>) {
  const supported = await getSupportedBrandColumns();
  const payload = prepareBrandPayload(brand, supported);
  delete payload.id;

  // Resilient update with schema retry if PostgREST reports missing column
  let attemptPayload = { ...payload };
  for (let attempt = 0; attempt < 8; attempt++) {
    const { data, error } = await supabase
      .from('brands')
      .update(attemptPayload)
      .eq('id', id)
      .select()
      .single();

    if (!error && data) {
      if (supportedColumnsCache) {
        Object.keys(data).forEach(k => supportedColumnsCache?.add(k));
      }
      return {
        ...data,
        status: data.status || (data.is_active !== false ? 'active' : 'hidden'),
      } as Brand;
    }

    if (error) {
      const missingMatch = error.message?.match(/Could not find the '([^']+)' column of 'brands'/i);
      if (missingMatch && missingMatch[1]) {
        const missingCol = missingMatch[1];
        console.warn(`Brand update: column '${missingCol}' missing in DB schema cache. Stripping and retrying.`);
        delete attemptPayload[missingCol];
        continue;
      }
      throw error;
    }
  }
  throw new Error('Failed to update brand after schema retries');
}

export async function deleteBrand(id: string) {
  const { error } = await supabase
    .from('brands')
    .delete()
    .eq('id', id);
  if (error) throw error;
}

export async function bulkUpdateBrands(updates: { id: string; changes: Partial<Brand> }[]) {
  const supported = await getSupportedBrandColumns();
  const promises = updates.map(u => {
    const payload = prepareBrandPayload(u.changes, supported);
    return supabase.from('brands').update(payload).eq('id', u.id);
  });
  await Promise.all(promises);
}
